//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMS.Admin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OMSen_EN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OMSen_EN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OMS.Admin.OMSen-EN", typeof(OMSen_EN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string resAdd {
            get {
                return ResourceManager.GetString("resAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string resCompanyName {
            get {
                return ResourceManager.GetString("resCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string resDelete {
            get {
                return ResourceManager.GetString("resDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic Name.
        /// </summary>
        public static string resGenericName {
            get {
                return ResourceManager.GetString("resGenericName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Deleted.
        /// </summary>
        public static string resIsDeleted {
            get {
                return ResourceManager.GetString("resIsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Prescription Required.
        /// </summary>
        public static string resIsPrescriptionRequired {
            get {
                return ResourceManager.GetString("resIsPrescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medicine Id.
        /// </summary>
        public static string resMedicineId {
            get {
                return ResourceManager.GetString("resMedicineId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medicine Name.
        /// </summary>
        public static string resMedicineName {
            get {
                return ResourceManager.GetString("resMedicineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do Not Display.
        /// </summary>
        public static string resNotToDisplay {
            get {
                return ResourceManager.GetString("resNotToDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Medical Store Admin.
        /// </summary>
        public static string resOnlineMedicalStore {
            get {
                return ResourceManager.GetString("resOnlineMedicalStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prescription Is Not Required.
        /// </summary>
        public static string resPrescriptionIsNotRequired {
            get {
                return ResourceManager.GetString("resPrescriptionIsNotRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prescription Is Required.
        /// </summary>
        public static string resPrescriptionIsRequired {
            get {
                return ResourceManager.GetString("resPrescriptionIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        public static string resToBeDisplayed {
            get {
                return ResourceManager.GetString("resToBeDisplayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To be displayed.
        /// </summary>
        public static string resToBeDisplayedInFrontEnd {
            get {
                return ResourceManager.GetString("resToBeDisplayedInFrontEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string resUpdate {
            get {
                return ResourceManager.GetString("resUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update / Delete.
        /// </summary>
        public static string resUpdateDelete {
            get {
                return ResourceManager.GetString("resUpdateDelete", resourceCulture);
            }
        }
    }
}
